services:
  distribu-te-mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: distribu-te-mssql-db
    environment:
      MSSQL_SA_PASSWORD: "d3pl0yNow!"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - distribu-te-vol-mssql-data:/var/opt/mssql/data
      - distribu-te-vol-mssql-log:/var/opt/mssql/log
      - distribu-te-vol-mssql-secrets:/var/opt/mssql/secrets
    networks:
      - net-distribu-te
        
  distribu-te-pgsql-db:
    image: postgres:17.4
    container_name: distribu-te-pgsql-db
    environment:
      POSTGRES_PASSWORD: $3c0nd2No-1
    ports:
      - "5432:5432"
    volumes:
      - distribu-te-vol-pgsql-data:/var/lib/postgresql/data
    networks:
      - net-distribu-te

  distribu-te-keycloak-identity:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: distribu-te-keycloak-identity
    environment:
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: Y0uShallN0tp@zz
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/distribu-Te/certs/kc_local_cert.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/distribu-Te/certs/kc_local_key.pem
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - distribu-te-vol-keycloak-identity:/opt/keycloak/data
      - ./_certs/kc:/opt/keycloak/distribu-Te/certs
    networks:
      - net-distribu-te
    command: start-dev
    
  distribu-te-prometheus:
    image: prom/prometheus:v2.53.4
    container_name: distribu-te-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./_configurations/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - distribu-te-vol-prometheus-data:/prometheus
    networks:
      - net-distribu-te
        
  distribu-te-grafana:
    image: grafana/grafana:11.6.0
    container_name: distribu-te-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: As-Graph1c@l-@$-it-g3tz
    volumes:
      - distribu-te-vol-grafana-data:/var/lib/grafana
    networks:
      - net-distribu-te

  distribu-te-jaeger:
    image: jaegertracing/all-in-one:1.67.0
    container_name: distribu-te-jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    networks:
      - net-distribu-te
  
  distribu-te-seq:
    image: datalust/seq:2024.3
    container_name: distribu-te-seq
    ports:
      - "80:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: admin
      # S3quenCial3
    volumes:
      - distribu-te-vol-seq-data:/data
    networks:
      - net-distribu-te
    
networks:
  net-distribu-te:
    driver: bridge
    name: net-distribu-te

volumes:
  distribu-te-vol-mssql-data:
    name: distribu-te-vol-mssql-data
  distribu-te-vol-mssql-log:
    name: distribu-te-vol-mssql-data
  distribu-te-vol-mssql-secrets:
    name: distribu-te-vol-mssql-data
  distribu-te-vol-keycloak-identity:
    name: distribu-te-vol-keycloak-identity
  distribu-te-vol-pgsql-data:
    name: distribu-te-vol-pgsql-data
  distribu-te-vol-grafana-data:
    name: distribu-te-vol-grafana-data
  distribu-te-vol-prometheus-data:
    name: distribu-te-vol-prometheus-data
  distribu-te-vol-seq-data:
    name: distribu-te-vol-seq-data
      
      
    
