global:
  scrape_interval: 5s
scrape_configs: 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'mut-teams-api'
    scheme: https
    static_configs:
      - targets: [ 'host.docker.internal:7101' ]