global:
  scrape_interval: 5s
scrape_configs: 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'mut-teams-api'
    static_configs:
      - targets: ['host.docker.internal:7101']
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'mut-projects-api'
    static_configs:
      - targets: [ 'host.docker.internal:7013' ]
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'aggr-teams-api'
    static_configs:
      - targets: [ 'host.docker.internal:7257' ]
    scheme: https
    tls_config:
      insecure_skip_verify: true